name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential

    - name: Build libft
      run: |
        make all
    
    - name: Clean up
      run: |
        make fclean
